# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{engine-tune}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Theodore Mills"]
  s.date = %q{2010-07-07}
  s.description = %q{Determine how well your engine will run under certain meteorological and geological conditions.}
  s.email = %q{theo@gutsbolts.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "engine-tune.gemspec",
     "lib/engine-tune.rb",
     "lib/engine-tune/calculations.rb",
     "lib/engine-tune/calculator.rb",
     "test/helper.rb",
     "test/test_calculations.rb",
     "test/test_calculator.rb",
     "test/test_engine_tune.rb",
     "test/test_suite.rb"
  ]
  s.homepage = %q{http://github.com/gutsbolts/engine-tune}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Determine how well your engine will run under certain meteorological and geological conditions.}
  s.test_files = [
    "test/helper.rb",
     "test/test_calculations.rb",
     "test/test_calculator.rb",
     "test/test_engine_tune.rb",
     "test/test_suite.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

